### ISSUE TITLE
Plugin GPL v2 Compatible

### ISSUE THREAD

**Issue by bilal-pp** [av01d/fontselect-jquery-plugin#1]
Hi,

Im sorry this is not an issue/bug. Wanted to ask if this plugin is GPL v2 compatible ?

Thanks,
Bilal Ahmed

**Comment by av01d** [comment]
Yep, it sure is. You're absolutely free to use it for whatever you want.

**Comment by bilal-pp** [comment]
Do I need to include the copyrights all the time where ever Im using it ?

**Comment by av01d** [comment]
Nope!

**Comment by bilal-pp** [comment]
thanks Arjan, appreciate your quick response :)
