### ISSUE TITLE
How to detect if the selected font is google font or system font?

### ISSUE THREAD

**Issue by bilal-pp** [av01d/fontselect-jquery-plugin#2]
We are developing a WordPress plugin in which I've used this plugin. I want the user to select a font I am adding it in the CSS via code. Now the problem is when the user selects a system font    we are not able to detect if its system font or google font and we end up adding link to google font. Could you please help me with this ?

**Comment by av01d** [comment]
When you initialise the plugin, you provide a list of system fonts (the `systemFonts` config var). When the user selects a font, you can check against this list. For example:

```
<input id="font1" type="text">
<script>
   var systemFonts = ['Arial', 'Courier+New', 'Helvetica', 'Times+New+Roman'];
   $('#font1')
   .fontselect({
      systemFonts: systemFonts
   })
  .on('change', function() {
      // Is this a system font?
      console.log('You picked font ' + this.value);
      if (systemFonts.indexOf(this.value) != -1) {
         console.log('This is a system font');
      }
});
</script>
```
