### ISSUE TITLE
Trigger('setFont') changes font family for all fontselect inputs

### ISSUE THREAD

**Issue by LiamDonnelly** [av01d/fontselect-jquery-plugin#3]
When calling the 'setFont' trigger for a certain fontSelect component all other fontSelect components will also change font family 

Same issue can be seem from the demo.
[https://av01d.github.io/fontselect-jquery-plugin/index.html](https://av01d.github.io/fontselect-jquery-plugin/index.html)

**Comment by av01d** [comment]
Thanks for reporting, the issue has been fixed in version 0.5, now available here!
