### ISSUE TITLE
Items hidden by search are still loaded

### ISSUE THREAD

**Issue by Diellan** [av01d/fontselect-jquery-plugin#4]
The `getVisibleFonts` function doesn't check to see if the individual lis are visible. This is a problem, because `.position().top` is 0 for invisible items, so at the top of the list it thinks all invisible items are visible and so it tries to load the fonts.

This is easiest to see by searching for something that doesn't exist, like "AAA", and then watching your network list go crazy as it loads all the fonts at once.

Simple adding `if ($(this).is(':hidden')) { return; }` inside the `$('li', this.$results).each(function(){` loop fixes this.

**Comment by av01d** [comment]
Thanks for your clear report, issue has been fixed!
