### ISSUE TITLE
Need help to fix the bug

### ISSUE THREAD

**Issue by iamappmaker** [av01d/fontselect-jquery-plugin#6]
Sorry for posting in wrong place because i don't know how to contact you regarding your fabricjs curved text code https://jsfiddle.net/av01d/4p0syzw3/ . If works perfectly as expected but when i loadfrom json it has bug. 

```
text.split is not a function
    at klass.getCircularText (fabric.js:29283)
    at klass.initialize (fabric.js:29197)
    at klass.eval [as initialize] (fabric.js:2015)
    at new klass (fabric.js:2080)
    at eval (fabric.js:14388)
    at onLoaded (fabric.js:1009)
    at eval (fabric.js:1025)
    at Array.forEach (<anonymous>)
    at Object.enlivenObjects (fabric.js:1022)
    at eval (fabric.js:14386)
```
Please help me to fix this. Thank you.

**Comment by av01d** [comment]
I've made some changes, hopefully it's fixed.
From now on: always (that is: each and every time) provide a fiddle.
I cannot test my fixes without a useful test case.

**Comment by iamappmaker** [comment]
Thank you for quick response. I just found the problem,  When load from json instead of text , entire curvedText object is set to text. 
`initialize: function(text, options) {`
	Here text = string when adding curved text but when loading from json text= complete curved text object.

I added a quick fix by checking the type

```
 if(typeof text=="string"){this.text=text } 
	else{	this.text=text.text;  } 
```

It works.
Is this correct way
