### ISSUE TITLE
How to reset to none

### ISSUE THREAD

**Issue by tbuegel** [av01d/fontselect-jquery-plugin#7]
Everything is working like expected. Great job! But I'm wondering how i can reset the selector to the state before any font was selected. 

`.trigger('setFont','')`
Setting to an empty font value is not working => jquery.fontselect.min.js?ver=0.3.2:formatted:123 Uncaught TypeError: Cannot read property 'offsetTop' of undefined

**Comment by av01d** [comment]
Development of this plugin has ended,  quite a while ago. I've made a (much better) successor, here: https://github.com/av01d/fontpicker-jquery-plugin
Please upgrade to that plugin, it also allows for showing a clear button. 
It does not have the "reset state" method you look for, but if you're willing to switch, I will implement it there.

**Comment by tbuegel** [comment]
Hi Arjan, thank you for your reply. I've seen this and tried the fontpicker. Then discovered the huge size difference:
jquery.fontpicker.min.js size is 102 KB (very big)
jquery.fontselect.min.js size is 16,8 KB (really lightweight)
The fontselect plugin is perfect for me, I only miss the reset method. But I think,  I can make a workaround with a reinitializing of the fontselect() method.
Are their other, maybe security issues not to use the fontselect plugin anymore?

**Comment by av01d** [comment]
The new plugin is only so big, as it comes with a list of all available Google fonts. In the old one, you need to define this list yourself. Take a look: https://github.com/av01d/fontpicker-jquery-plugin/blob/master/dist/jquery.fontpicker.js
So: the new plugin comes with all Google fonts readily available, in the old one you need to define them yourself, which can add up to the same amount of code.

**Comment by insad** [comment]
I made a small PHP script to download each night a fresh fonts list from Google and transform the same into the format used by the fontpicker plugin, and keep that list outside the picker. Besides as I have multiple font pickers, made a window.fontRegistry object where I load in only once this list, and keep track of the fonts really used in my app (for stylesheet injection).

**Comment by tbuegel** [comment]
@insad: nice idea. 
@av01d:  I did not review the code by now of both plugins, maybe I should (but so little time left for the extra things beside my dayly's tasks). I do not configure the Google fonts options, I only use empty systemFonts: [] and localFonts: [], cause I don't need them. But in the drop-down list all Google fonts are available to select from. See the attached screenshot.
![fontselect-sc](https://user-images.githubusercontent.com/8167606/96716170-f91e2a00-13a4-11eb-9b32-0821c685eaaf.PNG)
